// Generated by `figma-rust component-interfaces
// Using file version 2816422803"

/**
 * Component consts for Figma file GOV.UK Design System (Community)
 */
export const GOVUKDesignSystemCommunityConsts = {
  "🗝️  Styles and Components": {
    "Textarea": {
      label: [true, false],
      hint: [true, false],
      error: [false, true],
      characterHint: [true, false],
    },

    "Text input • Fluid": {
      width: ["Fill", "Full", "Three-quarters", "Two-thirds", "One-half", "One-third", "One-quarter"],
      labelLegend: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Text input • Fixed": {
      width: [2, 3, 4, 5, 10, 20],
      labelLegend: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Building blocks/Input • Affix/Label": {
      type: ["Suffix", "Prefix"],
    },

    "Building blocks/Text input/Input": {
      for: ["Text", "Number", "Textarea"],
      input: [false, true],
      focus: [false, true],
      error: [false, true],
    },

    "Text input • Affix": {
      width: [2, 3, 4, 5, 10, 20],
      prefix: [true, false],
      suffix: [true, false],
      labelLegend: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Tag": {
      colour: ["Default", "Grey", "Green", "Turquoise", "Blue", "Purple", "Pink", "Red", "Orange", "Yellow"],
    },

    "Building blocks/Tabs/List item": {
      active: [false, true],
    },

    "Building blocks/Table/Row": {
      type: ["Head", "Row"],
      columns: [2, 3],
    },

    "Table": {
      columns: [3, 2],
      rows: [3, 2, 4, 5],
    },

    "Building blocks/Summary list/Row": {
      border: [true, false],
      action: [true, false],
    },

    "Summary list": {
      border: [true, false],
      action: [true, false],
    },

    "Building blocks/Select/Input": {
      focus: [false, true],
    },

    "Select": {
      legend: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Section break": {
      none: ["Small", "Default", "Medium", "Large"],
    },

    "Building blocks/Radios/Item": {
      type: ["Default", "Hint", "Reveal"],
      selected: [false, true],
      focus: [false, true],
    },

    "Radios • Stacked": {
      legend: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Building blocks/Radios/Input": {
      selected: [false, true],
      focus: [true, false],
    },

    "Building blocks/Radios/Group": {
      options: [2, 3, 4, 5, 6, 7, 8, 9],
      orNone: [false, true],
    },

    "Building blocks/Radios • Small/Input": {
      selected: [false, true],
      hover: [false, true],
      focus: [false, true],
    },

    "Building blocks/Radios • Small/Item": {
      selected: [false, true],
      hover: [false, true],
      focus: [false, true],
    },

    "Building blocks/Radios • Small/Group": {
      options: [2, 3, 4, 5, 6, 7, 8, 9],
    },

    "Radios • Stacked • Small": {
      legend: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Radios • Inline • Small": {
      legend: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Radios • Inline": {
      legend: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Phase banner": {
      phase: ["Alpha", "Beta", "Live"],
    },

    "Building blocks/Pagination • Large/Link": {
      action: ["Next ->", "<- Previous"],
      state: ["Default", "Hover", "Focus"],
    },

    "Building blocks/Pagination • Large/List item": {
      active: [false, true],
      state: ["Default", "Hover", "Focus"],
      digits: ["Single", "Double/Triple"],
    },

    "Pagination • Large": {
      ellipses: [true, false],
      previous: [true, false],
      next: [true, false],
    },

    "Icons/Pagination": {
      type: ["Previous", "Next"],
    },

    "Building blocks/Pagination • Small/Link": {
      action: ["<- Previous", "-> Next"],
      hover: [false, true],
      focus: [false, true],
    },

    "Notification banner": {
      message: ["Important", "Success"],
      body: [true, false],
    },

    "List": {
      list: ["Bulleted", "Numbered", "Links"],
      leadIn: [true, false],
      spacing: ["Default", "Large"],
    },

    "Links": {
      size: ["16px", "19px"],
      colour: ["Blue", "Black", "Red", "White"],
      underlined: [true, false],
      state: ["Default", "Hover", "Focus"],
    },

    "Inset text": {
      list: [false, true],
      link: [false, true],
    },

    "Headings": {
      heading: ["Large", "Extra Large", "Medium"],
      caption: [true, false],
      padding: [false, true],
    },

    "Building blocks/Header • Super/Navigation item": {
      active: [false, true],
      state: ["Default", "Hover", "Focus"],
    },

    "Building blocks/Header • Super/Search": {
      active: [false, true],
      state: ["Default", "Hover", "Focus"],
    },

    "Header • Super": {
      breadcrumb: [false, true],
    },

    "Building blocks/Header/Navigation item": {
      active: [false, true],
      state: ["Default", "Hover", "Focus"],
    },

    "Building blocks/Header/Logo": {
      state: ["Default", "Hover", "Focus"],
    },

    "Header": {
      serviceName: [true, false],
      navigation: [false, true],
      phase: [false, true],
      backLink: [false, true],
    },

    "Footer": {
      navigation: [false, true],
      links: [false, true],
    },

    "Building blocks/File upload/Input": {
      focus: [false, true],
    },

    "File upload": {
      label: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Error summary": {
      errors: [1, 2, 3],
    },

    "Building blocks/Details/Summary": {
      expanded: [false, true],
      state: ["Default", "Hover", "Focus"],
    },

    "Icons/Details": {
      expanded: [false, true],
    },

    "Details": {
      expanded: [false, true],
      focus: [false, true],
    },

    "Date input": {
      legend: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Cookie banner": {
      responded: [false, true],
    },

    "Building blocks/Checkbox • Small/Input": {
      selected: [false, true],
      hover: [false, true],
      focus: [false, true],
    },

    "Building blocks/Checkbox • Small/Item": {
      selected: [false, true],
      hover: [false, true],
      focus: [false, true],
    },

    "Building blocks/Checkbox • Small/Group": {
      options: [3, 4, 5, 6, 7, 8, 9],
    },

    "Checkboxes • Small": {
      legend: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Building blocks/Checkboxes/Input": {
      checked: [false, true],
      focus: [false, true],
    },

    "Building blocks/Checkboxes/Item": {
      type: ["Default", "Hint", "Reveal"],
      selected: [false, true],
      focus: [false, true],
    },

    "Building blocks/Checkboxes/Group": {
      options: [3, 4, 5, 6, 7, 8, 9],
      orNone: [false, true],
    },

    "Checkboxes": {
      legend: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Building blocks/Content/Body": {
      list: [false, true],
    },

    "Button": {
      type: ["Primary", "Secondary", "Start", "Warning"],
      hover: [false, true],
      focus: [false, true],
      disabled: [false, true],
    },

    "Breadcrumb": {
      crumbs: [3, 2, 4, 5],
    },

    "Icons/Back link": {
      direction: ["Left", "Right"],
    },

    "Back link": {
      state: ["Default", "Hover", "Focus"],
    },

    "Building blocks/Accordion/Child": {
      summary: [false, true],
      expanded: [false, true],
      hover: [false, true],
      focus: [false, true],
    },

    "Building blocks/Accordion/Button": {
      expanded: [false, true],
      hover: [false, true],
      focus: [false, true],
    },

    "Building blocks/Accordion/Summary": {
      hover: [false, true],
      focus: [false, true],
    },

    "Building blocks/Accordion/Heading": {
      hover: [false, true],
      focus: [false, true],
    },

    "Icons/Accordion": {
      state: ["Closed", "Open"],
      focus: [false, true],
    },

    "Building blocks/Accordion/Toggle": {
      action: ["Show", "Hide"],
      hover: [false, true],
      active: [false, true],
    },

    "Building blocks/Accordion/Toggle all": {
      action: ["Show all", "Hide all"],
      hover: [false, true],
      active: [false, true],
    },
  },

  "📚  Patterns": {
    ".Building blocks/Step by step/Number": {
      type: ["First", "Middle", "Last"],
    },

    ".Building blocks/Step by step/or-and": {
      type: ["or", "and"],
    },

    ".Building blocks/Task list/Item": {
      state: ["Not started", "Cannot start yet", "In progress", "Completed"],
    },
  },
} as const;

/**
 * Component types for Figma file GOV.UK Design System (Community)
 */
export type GOVUKDesignSystemCommunityTypes = typeof GOVUKDesignSystemCommunityConsts;
