/**
* Component interfaces for Figma file GOV.UK Design System (Community)
*
* Generated by `figma-rust component-interfaces`
*
* Using file version 2816422803
*/
export interface GOVUKDesignSystemCommunityInterfaces {
  "🗝️  Styles and Components": {
    "Textarea": {
      label: boolean;
      hint: boolean;
      error: boolean;
      characterHint: boolean;
    };

    "Text input • Fluid": {
      width: "Fill" | "Full" | "Three-quarters" | "Two-thirds" | "One-half" | "One-third" | "One-quarter";
      labelLegend: boolean;
      hint: boolean;
      error: boolean;
    };

    "Text input • Fixed": {
      width: 2 | 3 | 4 | 5 | 10 | 20;
      labelLegend: boolean;
      hint: boolean;
      error: boolean;
    };

    "Building blocks/Input • Affix/Label": {
      type: "Suffix" | "Prefix";
    };

    "Building blocks/Text input/Input": {
      for: "Text" | "Number" | "Textarea";
      input: boolean;
      focus: boolean;
      error: boolean;
    };

    "Text input • Affix": {
      width: 2 | 3 | 4 | 5 | 10 | 20;
      prefix: boolean;
      suffix: boolean;
      labelLegend: boolean;
      hint: boolean;
      error: boolean;
    };

    "Tag": {
      colour: "Default" | "Grey" | "Green" | "Turquoise" | "Blue" | "Purple" | "Pink" | "Red" | "Orange" | "Yellow";
    };

    "Building blocks/Tabs/List item": {
      active: boolean;
    };

    "Building blocks/Table/Row": {
      type: "Head" | "Row";
      columns: 2 | 3;
    };

    "Table": {
      columns: 3 | 2;
      rows: 3 | 2 | 4 | 5;
    };

    "Building blocks/Summary list/Row": {
      border: boolean;
      action: boolean;
    };

    "Summary list": {
      border: boolean;
      action: boolean;
    };

    "Building blocks/Select/Input": {
      focus: boolean;
    };

    "Select": {
      legend: boolean;
      hint: boolean;
      error: boolean;
    };

    "Section break": {
      none: "Small" | "Default" | "Medium" | "Large";
    };

    "Building blocks/Radios/Item": {
      type: "Default" | "Hint" | "Reveal";
      selected: boolean;
      focus: boolean;
    };

    "Radios • Stacked": {
      legend: boolean;
      hint: boolean;
      error: boolean;
    };

    "Building blocks/Radios/Input": {
      selected: boolean;
      focus: boolean;
    };

    "Building blocks/Radios/Group": {
      options: 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
      orNone: boolean;
    };

    "Building blocks/Radios • Small/Input": {
      selected: boolean;
      hover: boolean;
      focus: boolean;
    };

    "Building blocks/Radios • Small/Item": {
      selected: boolean;
      hover: boolean;
      focus: boolean;
    };

    "Building blocks/Radios • Small/Group": {
      options: 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
    };

    "Radios • Stacked • Small": {
      legend: boolean;
      hint: boolean;
      error: boolean;
    };

    "Radios • Inline • Small": {
      legend: boolean;
      hint: boolean;
      error: boolean;
    };

    "Radios • Inline": {
      legend: boolean;
      hint: boolean;
      error: boolean;
    };

    "Phase banner": {
      phase: "Alpha" | "Beta" | "Live";
    };

    "Building blocks/Pagination • Large/Link": {
      action: "Next ->" | "<- Previous";
      state: "Default" | "Hover" | "Focus";
    };

    "Building blocks/Pagination • Large/List item": {
      active: boolean;
      state: "Default" | "Hover" | "Focus";
      digits: "Single" | "Double/Triple";
    };

    "Pagination • Large": {
      ellipses: boolean;
      previous: boolean;
      next: boolean;
    };

    "Icons/Pagination": {
      type: "Previous" | "Next";
    };

    "Building blocks/Pagination • Small/Link": {
      action: "<- Previous" | "-> Next";
      hover: boolean;
      focus: boolean;
    };

    "Notification banner": {
      message: "Important" | "Success";
      body: boolean;
    };

    "List": {
      list: "Bulleted" | "Numbered" | "Links";
      leadIn: boolean;
      spacing: "Default" | "Large";
    };

    "Links": {
      size: "16px" | "19px";
      colour: "Blue" | "Black" | "Red" | "White";
      underlined: boolean;
      state: "Default" | "Hover" | "Focus";
    };

    "Inset text": {
      list: boolean;
      link: boolean;
    };

    "Headings": {
      heading: "Large" | "Extra Large" | "Medium";
      caption: boolean;
      padding: boolean;
    };

    "Building blocks/Header • Super/Navigation item": {
      active: boolean;
      state: "Default" | "Hover" | "Focus";
    };

    "Building blocks/Header • Super/Search": {
      active: boolean;
      state: "Default" | "Hover" | "Focus";
    };

    "Header • Super": {
      breadcrumb: boolean;
    };

    "Building blocks/Header/Navigation item": {
      active: boolean;
      state: "Default" | "Hover" | "Focus";
    };

    "Building blocks/Header/Logo": {
      state: "Default" | "Hover" | "Focus";
    };

    "Header": {
      serviceName: boolean;
      navigation: boolean;
      phase: boolean;
      backLink: boolean;
    };

    "Footer": {
      navigation: boolean;
      links: boolean;
    };

    "Building blocks/File upload/Input": {
      focus: boolean;
    };

    "File upload": {
      label: boolean;
      hint: boolean;
      error: boolean;
    };

    "Error summary": {
      errors: 1 | 2 | 3;
    };

    "Building blocks/Details/Summary": {
      expanded: boolean;
      state: "Default" | "Hover" | "Focus";
    };

    "Icons/Details": {
      expanded: boolean;
    };

    "Details": {
      expanded: boolean;
      focus: boolean;
    };

    "Date input": {
      legend: boolean;
      hint: boolean;
      error: boolean;
    };

    "Cookie banner": {
      responded: boolean;
    };

    "Building blocks/Checkbox • Small/Input": {
      selected: boolean;
      hover: boolean;
      focus: boolean;
    };

    "Building blocks/Checkbox • Small/Item": {
      selected: boolean;
      hover: boolean;
      focus: boolean;
    };

    "Building blocks/Checkbox • Small/Group": {
      options: 3 | 4 | 5 | 6 | 7 | 8 | 9;
    };

    "Checkboxes • Small": {
      legend: boolean;
      hint: boolean;
      error: boolean;
    };

    "Building blocks/Checkboxes/Input": {
      checked: boolean;
      focus: boolean;
    };

    "Building blocks/Checkboxes/Item": {
      type: "Default" | "Hint" | "Reveal";
      selected: boolean;
      focus: boolean;
    };

    "Building blocks/Checkboxes/Group": {
      options: 3 | 4 | 5 | 6 | 7 | 8 | 9;
      orNone: boolean;
    };

    "Checkboxes": {
      legend: boolean;
      hint: boolean;
      error: boolean;
    };

    "Building blocks/Content/Body": {
      list: boolean;
    };

    "Button": {
      type: "Primary" | "Secondary" | "Start" | "Warning";
      hover: boolean;
      focus: boolean;
      disabled: boolean;
    };

    "Breadcrumb": {
      crumbs: 3 | 2 | 4 | 5;
    };

    "Icons/Back link": {
      direction: "Left" | "Right";
    };

    "Back link": {
      state: "Default" | "Hover" | "Focus";
    };

    "Building blocks/Accordion/Child": {
      summary: boolean;
      expanded: boolean;
      hover: boolean;
      focus: boolean;
    };

    "Building blocks/Accordion/Button": {
      expanded: boolean;
      hover: boolean;
      focus: boolean;
    };

    "Building blocks/Accordion/Summary": {
      hover: boolean;
      focus: boolean;
    };

    "Building blocks/Accordion/Heading": {
      hover: boolean;
      focus: boolean;
    };

    "Icons/Accordion": {
      state: "Closed" | "Open";
      focus: boolean;
    };

    "Building blocks/Accordion/Toggle": {
      action: "Show" | "Hide";
      hover: boolean;
      active: boolean;
    };

    "Building blocks/Accordion/Toggle all": {
      action: "Show all" | "Hide all";
      hover: boolean;
      active: boolean;
    };
  };

  "📚  Patterns": {
    ".Building blocks/Step by step/Number": {
      type: "First" | "Middle" | "Last";
    };

    ".Building blocks/Step by step/or-and": {
      type: "or" | "and";
    };

    ".Building blocks/Task list/Item": {
      state: "Not started" | "Cannot start yet" | "In progress" | "Completed";
    };
  };
};
