// Generated by `figma-rust component-interfaces
// Using file version 3189929566"

/**
 * Component consts for Figma file GOV.UK Design System (Community)
 */
export const GOVUKDesignSystemCommunityConsts = {
  "🗝️  Styles and Components": {
    "Textarea": {
      label: [true, false],
      hint: [true, false],
      error: [false, true],
      characterHint: [true, false],
    },

    "Text input • Fluid": {
      width: ["Fill", "Full", "Three-quarters", "Two-thirds", "One-half", "One-third", "One-quarter"],
      labelLegend: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Text input • Fixed": {
      viewport: ["Desktop", "Mobile"],
      width: [2, 3, 4, 5, 10, 20],
      labelLegend: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Building blocks/Input • Affix/Label": {
      viewport: ["Desktop", "Mobile"],
      type: ["Suffix", "Prefix"],
    },

    "Building blocks/Text input/Input": {
      viewport: ["Desktop", "Mobile"],
      for: ["Text", "Number", "Textarea"],
      input: [false, true],
      focus: [false, true],
      error: [false, true],
    },

    "Text input • Affix": {
      viewport: ["Desktop", "Mobile"],
      width: [2, 3, 4, 5, 10, 20],
      prefix: [true, false],
      suffix: [true, false],
      labelLegend: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Tag": {
      viewport: ["Desktop", "Mobile"],
      colour: ["Default", "Grey", "Green", "Turquoise", "Blue", "Purple", "Pink", "Red", "Orange", "Yellow"],
    },

    "Building blocks/Tabs/List item": {
      active: [false, true],
      hover: [false, true],
      focus: [false, true],
    },

    "Building blocks/Table/Row": {
      type: ["Head", "Row"],
      columns: [2, 3],
    },

    "Table": {
      columns: [3, 2],
      rows: [3, 2, 4, 5],
    },

    "Building blocks/Summary list/Row": {
      border: [true, false],
      action: [true, false],
    },

    "Summary list": {
      border: [true, false],
      action: [true, false],
    },

    "Building blocks/Select/Input": {
      viewport: ["Desktop", "Mobile"],
      focus: [false, true],
    },

    "Select": {
      viewport: ["Desktop", "Mobile"],
      legend: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Section break": {
      none: ["Small", "Default", "Medium", "Large"],
    },

    "Building blocks/Radios/Item": {
      viewport: ["Desktop", "Mobile"],
      type: ["Default", "Hint", "Reveal"],
      selected: [false, true],
      focus: [false, true],
    },

    "Radios • Stacked": {
      viewport: ["Desktop", "Mobile"],
      legend: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Building blocks/Radios/Input": {
      selected: [false, true],
      focus: [true, false],
    },

    "Building blocks/Radios/Group": {
      viewport: ["Desktop", "Mobile"],
      options: [2, 3, 4, 5, 6, 7, 8, 9],
      orNone: [false, true],
    },

    "Building blocks/Radios • Small/Input": {
      selected: [false, true],
      hover: [false, true],
      focus: [false, true],
    },

    "Building blocks/Radios • Small/Item": {
      viewport: ["Desktop", "Mobile"],
      selected: [false, true],
      hover: [false, true],
      focus: [false, true],
    },

    "Building blocks/Radios • Small/Group": {
      viewport: ["Desktop", "Mobile"],
      options: [2, 3, 4, 5, 6, 7, 8, 9],
    },

    "Radios • Stacked • Small": {
      viewport: ["Desktop", "Mobile"],
      legend: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Radios • Inline • Small": {
      viewport: ["Desktop", "Mobile"],
      legend: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Radios • Inline": {
      viewport: ["Desktop", "Mobile"],
      legend: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Phase banner": {
      viewport: ["Desktop", "Mobile"],
      phase: ["Alpha", "Beta", "Live"],
    },

    "Building blocks/Pagination • Large/Link": {
      action: ["Next ->", "<- Previous"],
      state: ["Default", "Hover", "Focus"],
    },

    "Building blocks/Pagination • Large/List item": {
      active: [false, true],
      state: ["Default", "Hover", "Focus"],
      digits: ["Single", "Double/Triple"],
    },

    "Pagination • Large": {
      ellipses: [true, false],
      previous: [true, false],
      next: [true, false],
    },

    "Icons/Pagination": {
      type: ["Previous", "Next"],
    },

    "Building blocks/Pagination • Small/Link": {
      action: ["<- Previous", "-> Next"],
      hover: [false, true],
      focus: [false, true],
    },

    "Notification banner": {
      viewport: ["Desktop", "Mobile"],
      message: ["Important", "Success"],
      body: [false, true],
    },

    "List": {
      viewport: ["Desktop", "Mobile"],
      list: ["Bulleted", "Numbered", "Links"],
      leadIn: [true, false],
      spacing: ["Default", "Large"],
    },

    "Links": {
      viewport: ["Desktop", "Mobile"],
      size: ["Small", "Default"],
      colour: ["Blue", "Black", "Red", "White"],
      underlined: [true, false],
      state: ["Default", "Hover", "Focus"],
    },

    "Inset text": {
      viewport: ["Desktop", "Mobile"],
      list: [false, true],
      link: [false, true],
    },

    "Headings": {
      viewport: ["Desktop", "Mobile"],
      heading: ["Large", "Extra Large", "Medium"],
      caption: [true, false],
      padding: [false, true],
    },

    "Building blocks/Header • Super/Navigation item": {
      active: [false, true],
      state: ["Default", "Hover", "Focus"],
    },

    "Building blocks/Header • Super/Search": {
      active: [false, true],
      state: ["Default", "Hover", "Focus"],
    },

    "Header • Super": {
      breadcrumb: [false, true],
    },

    "Building blocks/Header/Navigation item": {
      active: [false, true],
      state: ["Default", "Hover", "Focus"],
    },

    "Building blocks/Header/Logo": {
      state: ["Default", "Hover", "Focus"],
    },

    "Header": {
      serviceName: [true, false],
      navigation: [false, true],
      phase: [false, true],
      backLink: [false, true],
    },

    "Footer": {
      navigation: [false, true],
      links: [false, true],
    },

    "Building blocks/File upload/Input": {
      viewport: ["Desktop", "Mobile"],
      focus: [false, true],
    },

    "File upload": {
      viewport: ["Desktop", "Mobile"],
      label: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Error summary": {
      viewport: ["Desktop", "Mobile"],
      errors: [1, 2, 3],
    },

    "Building blocks/Details/Summary": {
      viewport: ["Desktop", "Mobile"],
      expanded: [false, true],
      state: ["Default", "Hover", "Focus"],
    },

    "Icons/Details": {
      expanded: [false, true],
    },

    "Details": {
      viewport: ["Desktop", "Mobile"],
      expanded: [false, true],
      focus: [false, true],
    },

    "Date input": {
      viewport: ["Desktop"],
      legend: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Cookie banner": {
      responded: [false, true],
    },

    "Building blocks/Checkbox • Small/Input": {
      selected: [false, true],
      hover: [false, true],
      focus: [false, true],
    },

    "Building blocks/Checkbox • Small/Item": {
      viewport: ["Desktop", "Mobile"],
      selected: [false, true],
      hover: [false, true],
      focus: [false, true],
    },

    "Building blocks/Checkbox • Small/Group": {
      viewport: ["Desktop", "Mobile"],
      options: [3, 4, 5, 6, 7, 8, 9],
    },

    "Checkboxes • Small": {
      viewport: ["Desktop", "Mobile"],
      legend: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Building blocks/Checkboxes/Input": {
      checked: [false, true],
      focus: [false, true],
    },

    "Building blocks/Checkboxes/Item": {
      viewport: ["Desktop", "Mobile"],
      type: ["Default", "Hint", "Reveal"],
      selected: [false, true],
      focus: [false, true],
    },

    "Building blocks/Checkboxes/Group": {
      viewport: ["Desktop", "Mobile"],
      options: [3, 4, 5, 6, 7, 8, 9],
      orNone: [false, true],
    },

    "Checkboxes": {
      viewport: ["Desktop", "Mobile"],
      legend: [true, false],
      hint: [true, false],
      error: [false, true],
    },

    "Building blocks/Content/Body": {
      viewport: ["Desktop", "Mobile"],
      list: [false, true],
    },

    "Button": {
      viewport: ["Desktop", "Mobile"],
      type: ["Primary", "Secondary", "Warning", "Start"],
      hover: [false, true],
      focus: [false, true],
      disabled: [false, true],
    },

    "Breadcrumb": {
      viewport: ["Desktop", "Mobile"],
      crumbs: [3, 2, 4, 5],
    },

    "Icons/Back link": {
      direction: ["Left", "Right"],
    },

    "Back link": {
      viewport: ["Desktop", "Mobile"],
      state: ["Default", "Hover", "Focus"],
    },

    "Building blocks/Accordion/Child": {
      summary: [false, true],
      expanded: [false, true],
      hover: [false, true],
      focus: [false, true],
    },

    "Building blocks/Accordion/Button": {
      expanded: [false, true],
      hover: [false, true],
      focus: [false, true],
    },

    "Building blocks/Accordion/Summary": {
      hover: [false, true],
      focus: [false, true],
    },

    "Building blocks/Accordion/Heading": {
      hover: [false, true],
      focus: [false, true],
    },

    "Icons/Accordion": {
      state: ["Closed", "Open"],
      focus: [false, true],
    },

    "Building blocks/Accordion/Toggle": {
      action: ["Show", "Hide"],
      hover: [false, true],
      active: [false, true],
    },

    "Building blocks/Accordion/Toggle all": {
      action: ["Show all", "Hide all"],
      hover: [false, true],
      active: [false, true],
    },

    "Warning text": {
      viewport: ["Desktop", "Mobile"],
    },

    "Panel": {
      viewport: ["Desktop", "Mobile"],
    },
  },

  "📚  Patterns": {
    ".Building blocks/Step by step/Number": {
      type: ["First", "Middle", "Last"],
    },

    ".Building blocks/Step by step/or-and": {
      type: ["or", "and"],
    },

    ".Building blocks/Task list/Item": {
      state: ["Not started", "Cannot start yet", "In progress", "Completed"],
    },
  },
} as const;

/**
 * Component types for Figma file GOV.UK Design System (Community)
 */
export interface GOVUKDesignSystemCommunityTypes {
  "🗝️  Styles and Components": {
    "Textarea": {
      label: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Textarea"]["label"][number];
      hint: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Textarea"]["hint"][number];
      error: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Textarea"]["error"][number];
      characterHint: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Textarea"]["characterHint"][number];
    };

    "Text input • Fluid": {
      width: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Text input • Fluid"]["width"][number];
      labelLegend: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Text input • Fluid"]["labelLegend"][number];
      hint: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Text input • Fluid"]["hint"][number];
      error: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Text input • Fluid"]["error"][number];
    };

    "Text input • Fixed": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Text input • Fixed"]["viewport"][number];
      width: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Text input • Fixed"]["width"][number];
      labelLegend: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Text input • Fixed"]["labelLegend"][number];
      hint: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Text input • Fixed"]["hint"][number];
      error: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Text input • Fixed"]["error"][number];
    };

    "Building blocks/Input • Affix/Label": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Input • Affix/Label"]["viewport"][number];
      type: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Input • Affix/Label"]["type"][number];
    };

    "Building blocks/Text input/Input": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Text input/Input"]["viewport"][number];
      for: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Text input/Input"]["for"][number];
      input: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Text input/Input"]["input"][number];
      focus: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Text input/Input"]["focus"][number];
      error: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Text input/Input"]["error"][number];
    };

    "Text input • Affix": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Text input • Affix"]["viewport"][number];
      width: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Text input • Affix"]["width"][number];
      prefix: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Text input • Affix"]["prefix"][number];
      suffix: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Text input • Affix"]["suffix"][number];
      labelLegend: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Text input • Affix"]["labelLegend"][number];
      hint: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Text input • Affix"]["hint"][number];
      error: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Text input • Affix"]["error"][number];
    };

    "Tag": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Tag"]["viewport"][number];
      colour: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Tag"]["colour"][number];
    };

    "Building blocks/Tabs/List item": {
      active: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Tabs/List item"]["active"][number];
      hover: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Tabs/List item"]["hover"][number];
      focus: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Tabs/List item"]["focus"][number];
    };

    "Building blocks/Table/Row": {
      type: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Table/Row"]["type"][number];
      columns: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Table/Row"]["columns"][number];
    };

    "Table": {
      columns: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Table"]["columns"][number];
      rows: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Table"]["rows"][number];
    };

    "Building blocks/Summary list/Row": {
      border: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Summary list/Row"]["border"][number];
      action: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Summary list/Row"]["action"][number];
    };

    "Summary list": {
      border: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Summary list"]["border"][number];
      action: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Summary list"]["action"][number];
    };

    "Building blocks/Select/Input": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Select/Input"]["viewport"][number];
      focus: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Select/Input"]["focus"][number];
    };

    "Select": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Select"]["viewport"][number];
      legend: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Select"]["legend"][number];
      hint: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Select"]["hint"][number];
      error: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Select"]["error"][number];
    };

    "Section break": {
      none: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Section break"]["none"][number];
    };

    "Building blocks/Radios/Item": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Radios/Item"]["viewport"][number];
      type: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Radios/Item"]["type"][number];
      selected: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Radios/Item"]["selected"][number];
      focus: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Radios/Item"]["focus"][number];
    };

    "Radios • Stacked": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Radios • Stacked"]["viewport"][number];
      legend: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Radios • Stacked"]["legend"][number];
      hint: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Radios • Stacked"]["hint"][number];
      error: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Radios • Stacked"]["error"][number];
    };

    "Building blocks/Radios/Input": {
      selected: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Radios/Input"]["selected"][number];
      focus: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Radios/Input"]["focus"][number];
    };

    "Building blocks/Radios/Group": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Radios/Group"]["viewport"][number];
      options: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Radios/Group"]["options"][number];
      orNone: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Radios/Group"]["orNone"][number];
    };

    "Building blocks/Radios • Small/Input": {
      selected: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Radios • Small/Input"]["selected"][number];
      hover: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Radios • Small/Input"]["hover"][number];
      focus: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Radios • Small/Input"]["focus"][number];
    };

    "Building blocks/Radios • Small/Item": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Radios • Small/Item"]["viewport"][number];
      selected: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Radios • Small/Item"]["selected"][number];
      hover: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Radios • Small/Item"]["hover"][number];
      focus: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Radios • Small/Item"]["focus"][number];
    };

    "Building blocks/Radios • Small/Group": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Radios • Small/Group"]["viewport"][number];
      options: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Radios • Small/Group"]["options"][number];
    };

    "Radios • Stacked • Small": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Radios • Stacked • Small"]["viewport"][number];
      legend: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Radios • Stacked • Small"]["legend"][number];
      hint: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Radios • Stacked • Small"]["hint"][number];
      error: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Radios • Stacked • Small"]["error"][number];
    };

    "Radios • Inline • Small": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Radios • Inline • Small"]["viewport"][number];
      legend: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Radios • Inline • Small"]["legend"][number];
      hint: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Radios • Inline • Small"]["hint"][number];
      error: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Radios • Inline • Small"]["error"][number];
    };

    "Radios • Inline": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Radios • Inline"]["viewport"][number];
      legend: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Radios • Inline"]["legend"][number];
      hint: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Radios • Inline"]["hint"][number];
      error: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Radios • Inline"]["error"][number];
    };

    "Phase banner": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Phase banner"]["viewport"][number];
      phase: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Phase banner"]["phase"][number];
    };

    "Building blocks/Pagination • Large/Link": {
      action: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Pagination • Large/Link"]["action"][number];
      state: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Pagination • Large/Link"]["state"][number];
    };

    "Building blocks/Pagination • Large/List item": {
      active: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Pagination • Large/List item"]["active"][number];
      state: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Pagination • Large/List item"]["state"][number];
      digits: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Pagination • Large/List item"]["digits"][number];
    };

    "Pagination • Large": {
      ellipses: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Pagination • Large"]["ellipses"][number];
      previous: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Pagination • Large"]["previous"][number];
      next: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Pagination • Large"]["next"][number];
    };

    "Icons/Pagination": {
      type: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Icons/Pagination"]["type"][number];
    };

    "Building blocks/Pagination • Small/Link": {
      action: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Pagination • Small/Link"]["action"][number];
      hover: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Pagination • Small/Link"]["hover"][number];
      focus: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Pagination • Small/Link"]["focus"][number];
    };

    "Notification banner": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Notification banner"]["viewport"][number];
      message: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Notification banner"]["message"][number];
      body: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Notification banner"]["body"][number];
    };

    "List": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["List"]["viewport"][number];
      list: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["List"]["list"][number];
      leadIn: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["List"]["leadIn"][number];
      spacing: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["List"]["spacing"][number];
    };

    "Links": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Links"]["viewport"][number];
      size: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Links"]["size"][number];
      colour: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Links"]["colour"][number];
      underlined: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Links"]["underlined"][number];
      state: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Links"]["state"][number];
    };

    "Inset text": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Inset text"]["viewport"][number];
      list: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Inset text"]["list"][number];
      link: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Inset text"]["link"][number];
    };

    "Headings": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Headings"]["viewport"][number];
      heading: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Headings"]["heading"][number];
      caption: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Headings"]["caption"][number];
      padding: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Headings"]["padding"][number];
    };

    "Building blocks/Header • Super/Navigation item": {
      active: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Header • Super/Navigation item"]["active"][number];
      state: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Header • Super/Navigation item"]["state"][number];
    };

    "Building blocks/Header • Super/Search": {
      active: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Header • Super/Search"]["active"][number];
      state: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Header • Super/Search"]["state"][number];
    };

    "Header • Super": {
      breadcrumb: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Header • Super"]["breadcrumb"][number];
    };

    "Building blocks/Header/Navigation item": {
      active: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Header/Navigation item"]["active"][number];
      state: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Header/Navigation item"]["state"][number];
    };

    "Building blocks/Header/Logo": {
      state: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Header/Logo"]["state"][number];
    };

    "Header": {
      serviceName: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Header"]["serviceName"][number];
      navigation: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Header"]["navigation"][number];
      phase: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Header"]["phase"][number];
      backLink: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Header"]["backLink"][number];
    };

    "Footer": {
      navigation: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Footer"]["navigation"][number];
      links: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Footer"]["links"][number];
    };

    "Building blocks/File upload/Input": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/File upload/Input"]["viewport"][number];
      focus: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/File upload/Input"]["focus"][number];
    };

    "File upload": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["File upload"]["viewport"][number];
      label: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["File upload"]["label"][number];
      hint: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["File upload"]["hint"][number];
      error: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["File upload"]["error"][number];
    };

    "Error summary": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Error summary"]["viewport"][number];
      errors: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Error summary"]["errors"][number];
    };

    "Building blocks/Details/Summary": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Details/Summary"]["viewport"][number];
      expanded: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Details/Summary"]["expanded"][number];
      state: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Details/Summary"]["state"][number];
    };

    "Icons/Details": {
      expanded: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Icons/Details"]["expanded"][number];
    };

    "Details": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Details"]["viewport"][number];
      expanded: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Details"]["expanded"][number];
      focus: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Details"]["focus"][number];
    };

    "Date input": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Date input"]["viewport"][number];
      legend: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Date input"]["legend"][number];
      hint: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Date input"]["hint"][number];
      error: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Date input"]["error"][number];
    };

    "Cookie banner": {
      responded: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Cookie banner"]["responded"][number];
    };

    "Building blocks/Checkbox • Small/Input": {
      selected: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Checkbox • Small/Input"]["selected"][number];
      hover: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Checkbox • Small/Input"]["hover"][number];
      focus: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Checkbox • Small/Input"]["focus"][number];
    };

    "Building blocks/Checkbox • Small/Item": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Checkbox • Small/Item"]["viewport"][number];
      selected: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Checkbox • Small/Item"]["selected"][number];
      hover: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Checkbox • Small/Item"]["hover"][number];
      focus: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Checkbox • Small/Item"]["focus"][number];
    };

    "Building blocks/Checkbox • Small/Group": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Checkbox • Small/Group"]["viewport"][number];
      options: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Checkbox • Small/Group"]["options"][number];
    };

    "Checkboxes • Small": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Checkboxes • Small"]["viewport"][number];
      legend: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Checkboxes • Small"]["legend"][number];
      hint: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Checkboxes • Small"]["hint"][number];
      error: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Checkboxes • Small"]["error"][number];
    };

    "Building blocks/Checkboxes/Input": {
      checked: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Checkboxes/Input"]["checked"][number];
      focus: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Checkboxes/Input"]["focus"][number];
    };

    "Building blocks/Checkboxes/Item": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Checkboxes/Item"]["viewport"][number];
      type: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Checkboxes/Item"]["type"][number];
      selected: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Checkboxes/Item"]["selected"][number];
      focus: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Checkboxes/Item"]["focus"][number];
    };

    "Building blocks/Checkboxes/Group": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Checkboxes/Group"]["viewport"][number];
      options: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Checkboxes/Group"]["options"][number];
      orNone: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Checkboxes/Group"]["orNone"][number];
    };

    "Checkboxes": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Checkboxes"]["viewport"][number];
      legend: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Checkboxes"]["legend"][number];
      hint: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Checkboxes"]["hint"][number];
      error: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Checkboxes"]["error"][number];
    };

    "Building blocks/Content/Body": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Content/Body"]["viewport"][number];
      list: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Content/Body"]["list"][number];
    };

    "Button": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Button"]["viewport"][number];
      type: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Button"]["type"][number];
      hover: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Button"]["hover"][number];
      focus: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Button"]["focus"][number];
      disabled: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Button"]["disabled"][number];
    };

    "Breadcrumb": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Breadcrumb"]["viewport"][number];
      crumbs: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Breadcrumb"]["crumbs"][number];
    };

    "Icons/Back link": {
      direction: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Icons/Back link"]["direction"][number];
    };

    "Back link": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Back link"]["viewport"][number];
      state: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Back link"]["state"][number];
    };

    "Building blocks/Accordion/Child": {
      summary: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Accordion/Child"]["summary"][number];
      expanded: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Accordion/Child"]["expanded"][number];
      hover: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Accordion/Child"]["hover"][number];
      focus: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Accordion/Child"]["focus"][number];
    };

    "Building blocks/Accordion/Button": {
      expanded: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Accordion/Button"]["expanded"][number];
      hover: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Accordion/Button"]["hover"][number];
      focus: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Accordion/Button"]["focus"][number];
    };

    "Building blocks/Accordion/Summary": {
      hover: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Accordion/Summary"]["hover"][number];
      focus: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Accordion/Summary"]["focus"][number];
    };

    "Building blocks/Accordion/Heading": {
      hover: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Accordion/Heading"]["hover"][number];
      focus: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Accordion/Heading"]["focus"][number];
    };

    "Icons/Accordion": {
      state: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Icons/Accordion"]["state"][number];
      focus: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Icons/Accordion"]["focus"][number];
    };

    "Building blocks/Accordion/Toggle": {
      action: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Accordion/Toggle"]["action"][number];
      hover: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Accordion/Toggle"]["hover"][number];
      active: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Accordion/Toggle"]["active"][number];
    };

    "Building blocks/Accordion/Toggle all": {
      action: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Accordion/Toggle all"]["action"][number];
      hover: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Accordion/Toggle all"]["hover"][number];
      active: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Building blocks/Accordion/Toggle all"]["active"][number];
    };

    "Warning text": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Warning text"]["viewport"][number];
    };

    "Panel": {
      viewport: typeof GOVUKDesignSystemCommunityConsts["🗝️  Styles and Components"]["Panel"]["viewport"][number];
    };
  };

  "📚  Patterns": {
    ".Building blocks/Step by step/Number": {
      type: typeof GOVUKDesignSystemCommunityConsts["📚  Patterns"][".Building blocks/Step by step/Number"]["type"][number];
    };

    ".Building blocks/Step by step/or-and": {
      type: typeof GOVUKDesignSystemCommunityConsts["📚  Patterns"][".Building blocks/Step by step/or-and"]["type"][number];
    };

    ".Building blocks/Task list/Item": {
      state: typeof GOVUKDesignSystemCommunityConsts["📚  Patterns"][".Building blocks/Task list/Item"]["state"][number];
    };
  };
};
