name: Release
on:
  push:
    tags:
      - "file-tools-*"
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          name: figma-file-tools-${{ runner.arch }}-${{ runner.os }}
          path:
            target/release/figma-file-tools${{ runner.os == 'Windows' && '.exe'
            || '' }}
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "figma-file-tools-X64-Linux,figma-file-tools-X64-Windows,figma-file-tools-X64-macOS"
