name: Release
on:
  push:
    tags:
      - "file-tools-*"
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          name: figma-file-tools-${{ runner.arch }}-${{ runner.os }}
          path:
            target/release/figma-file-tools${{ runner.os == 'Windows' && '.exe'
            || '' }}
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: figma-file-tools-X64-Linux
          path: figma-file-tools-X64-Linux
      - run: "chmod +x figma-file-tools-X64-Linux/figma-file-tools"
      - run:
          tar --create --gzip --file figma-file-tools-X64-Linux.tar.gz
          --directory figma-file-tools-X64-Linux figma-file-tools
      - uses: actions/download-artifact@v3
        with:
          name: figma-file-tools-X64-Windows
          path: figma-file-tools-X64-Windows
      - uses: actions/download-artifact@v3
        with:
          name: figma-file-tools-X64-macOS
          path: figma-file-tools-X64-macOS
      - run: "chmod +x figma-file-tools-X64-macOS/figma-file-tools"
      - run:
          tar --create --gzip --file figma-file-tools-X64-macOS.tar.gz
          --directory figma-file-tools-X64-macOS figma-file-tools
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "figma-file-tools-X64-Linux.tar.gz,figma-file-tools-X64-Windows/figma-file-tools.exe,figma-file-tools-X64-macOS.tar.gz"
